### ISSUE TITLE
Content for Sponsors

### ISSUE THREAD

**Issue by katansapdevelop** [SAPOnlineTrack/saponlinetrack-gen#14]
Should we include site content for sponsors?  I.e. a page of sponsors or space on the home page for bigger sponsors?

**Comment by rsletta** [comment]
yes, that is a good idea. At least a page  listing the sponsors.

**Comment by katansapdevelop** [comment]
Completed and tested on ios for mobile rendering 
![image](https://user-images.githubusercontent.com/5642886/80495146-e3f2b080-89aa-11ea-852d-299358ff014c.png)
